#!/usr/bin/env bash

: "${TELEGRAM_BOT_TOKEN:?}"

API_URL="${TG_API:-https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}}"
DOWNLOADS_DIR="${DOWNLOADS_DIR:-/downloads}"
SHARED_DIR="${SHARED_DIR:-/app/shared}"
PUBLIC_BASE_URL_FILE="${PUBLIC_BASE_URL_FILE:-${SHARED_DIR}/public-base-url.txt}"
SLEEP_SECONDS="${SLEEP_SECONDS:-3}"
CLEANUP_INTERVAL_SECONDS="${CLEANUP_INTERVAL_SECONDS:-3600}"
DOWNLOAD_TTL_SECONDS="${DOWNLOAD_TTL_SECONDS:-86400}"
MAX_DOWNLOAD_FAILS="${MAX_DOWNLOAD_FAILS:-3}"
MAX_NOTIFY_FAILS="${MAX_NOTIFY_FAILS:-3}"
YT_DLP_UPDATE_INTERVAL_SECONDS="${YT_DLP_UPDATE_INTERVAL_SECONDS:-3600}"
SERVER_PORT="${SERVER_PORT:-3000}"
TUNNEL_URL="${TUNNEL_URL:-http://127.0.0.1:${SERVER_PORT}}"
VERSION="${VERSION:-dev}"
