services:
  ms-ingest:
    image: tupinumboor/ydtb-ingest
    build:
      context: ./ms-ingest
      tags:
        - "tupinumboor/ydtb-ingest:local"
        - "tupinumboor/ydtb-ingest:latest"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./app/requested:/app/requested

  ms-server:
    image: tupinumboor/ydtb-server
    build:
      context: ./ms-server
      tags:
        - "tupinumboor/ydtb-server:local"
        - "tupinumboor/ydtb-server:latest"
    restart: unless-stopped
    volumes:
      - ./app/published:/app/published

  ms-cloudflared:
    image: tupinumboor/ydtb-cloudflared
    build:
      context: ./ms-cloudflared
      tags:
        - "tupinumboor/ydtb-cloudflared:local"
        - "tupinumboor/ydtb-cloudflared:latest"
    restart: unless-stopped
    environment:
      TUNNEL_URL: http://ms-server:3000
    volumes:
      - ./app/shared:/app/shared
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://127.0.0.1:20241/ready >/dev/null 2>&1"]
      interval: 1s
      timeout: 1s
      retries: 30

  ms-downloader:
    image: tupinumboor/ydtb-downloader
    build:
      context: ./ms-downloader
      tags:
        - "tupinumboor/ydtb-downloader:local"
        - "tupinumboor/ydtb-downloader:latest"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./app/requested:/app/requested
      - ./app/downloading:/app/downloading
      - ./app/downloaded:/app/downloaded
      - ./app/failed:/app/failed

  ms-publisher:
    image: tupinumboor/ydtb-publisher
    build:
      context: ./ms-publisher
      tags:
        - "tupinumboor/ydtb-publisher:local"
        - "tupinumboor/ydtb-publisher:latest"
    restart: unless-stopped
    depends_on:
      ms-cloudflared:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./app/downloaded:/app/downloaded
      - ./app/published:/app/published
      - ./app/failed:/app/failed
      - ./app/shared:/app/shared

  ms-cleaner:
    image: ghcr.io/tupinumboor/pipeline-cleaner:1.1.0
    restart: unless-stopped
    environment:
      DIR_MAX_AGE_DAYS: 2
    volumes:
      - ./app/published:/clean/published
      - ./app/failed:/clean/failed
