services:
  ms-ingest:
    build:
      context: ./ms-ingest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./app/requested:/app/requested
      - ./app/shared:/app/shared
